import Head from 'next/head'
import React, { Fragment } from 'react'
import Link from 'next/link'
import Router from 'next/router'
import NProgress from 'nprogress'
import 'nprogress/nprogress.css'
Router.onRouteChangeStart = url => NProgress.start();
Router.onRouteChangeComplete = url => NProgress.done();
Router.onRouteChangeError = url => NProgress.done();

const General = ({ children }) => {
    const head = () => (
        <Fragment>
            <title>Welcome to Knock</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Fragment>
    )

    return (
        <Fragment>
            {head()}<div>{children}</div>
        </Fragment>
    )
}

export default General